name: tofu Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:


env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  GITHUB_ORGANIZATION: ${{ github.repository_owner }}
  TF_VAR_github_org: ${{ github.repository_owner }}
  TF_VAR_aws_role_github_actions: ${{ secrets.AWS_ROLE_GITHUB_ACTIONS }}
  TF_VAR_state_bucket_name: ${{ secrets.TF_STATE_BUCKET }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GEEKZONEBOT_APP_ID }}
          private_key: ${{ secrets.GEEKZONEBOT_PRIVATE_KEY }}

      - name: Checkout Repository
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_PREFIX }}${{ secrets.AWS_ROLE_GITHUB_ACTIONS }}
          aws-region: eu-west-2

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false

      - name: Get membermojo data and process
        id: get_membermojo
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          MEMBERMOJO_EMAIL: ${{ secrets.MEMBERMOJO_EMAIL }}
          MEMBERMOJO_PASSWORD: ${{ secrets.MEMBERMOJO_PASSWORD }}
        run: |
          echo "${{ secrets.MEMBERMOJO_COOKIE }}" > cookies.txt
          echo "🍪 Checking for cookie"
          if ! grep -q "# Netscape HTTP Cookie File" cookies.txt; then
            echo "❌ No cookie"
            exit 1
          fi
          echo "👍 Good cookie"
          
          echo "Checking for curl"
          if ! curl --version; then
            echo "curl not found"
            exit 1
          fi          
          echo "👍 Found curl"
          
          echo "Running Curl to sign in"
          curl --cookie cookies.txt --cookie-jar cookies.txt --output signin.html --data "email=$MEMBERMOJO_EMAIL&password=$MEMBERMOJO_PASSWORD" https://membermojo.co.uk/geekzone/signin_password
          
          echo "Running Curl to download members"
          curl --cookie cookies.txt --output members.csv https://membermojo.co.uk/geekzone/membership/download_members
          
          echo "💾 Checking for member data"
          if grep -q "<!DOCTYPE html>" members.csv; then
            echo "Error: ❌ Downloaded file is an HTML error page"
            exit 1
          fi
          echo "👍 Good member data"
                    
          python3 src/github_usernames_roles_current.py
          rm members.csv


      - name: Build tofu Plan
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          TF_VAR_region: ${{ env.AWS_REGION }}
        run: |
          cd terraform
          tofu init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ github.event.repository.name }}/terraform.tfstate" \
            -backend-config="region=$AWS_REGION"
          tofu plan -no-color -out=tfplan
          tofu show -no-color -json tfplan > plan.json

      - name: tofu Apply
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
        run: tofu apply terraform/tfplan